services:
  api-1:
    image: guilhermegules/rinha-node:latest
    container_name: api-1
    command: npm run start:api
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rinha
      - REDIS_URL=redis://redis:6379
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - PORT=3000
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "80MB"

  api-2:
    image: guilhermegules/rinha-node:latest
    container_name: api-2
    command: npm run start:api
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rinha
      - REDIS_URL=redis://redis:6379
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - PORT=3000
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "80MB"

  worker:
    image: guilhermegules/rinha-node:latest
    command: npm run start:worker
    container_name: worker
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rinha
      - REDIS_URL=redis://redis:6379
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "40MB"

  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "100MB"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
